apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: sparkapp
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "sparkapp:latest"
  imagePullPolicy: IfNotPresent
  mainClass: com.example.DeltaMinioApp
  mainApplicationFile: "local:///opt/spark/apps/sparkapp.jar"
  sparkVersion: "3.5.3"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "1g"
    memoryLimit: "1.2g"
    labels:
      version: 3.5.3
    serviceAccount: spark
    env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: minio-credentials
            key: access-key
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: minio-credentials
            key: secret-key
  executor:
    cores: 1
    coreLimit: "1200m"
    instances: 1
    memory: "1g"
    memoryLimit: "1.2g"
    labels:
      version: 3.5.3
    env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: minio-credentials
            key: access-key
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: minio-credentials
            key: secret-key
  sparkConf:
    "spark.hadoop.fs.s3a.endpoint": "http://192.168.68.103:9000"
    "spark.app.s3.table.path": "s3a://datalake/dummy/test" 