apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: demo-db
spec:
  instances: 1
  storage:
    size: 10Gi
  bootstrap:
    initdb:
      database: demo
      owner: demo   
  postgresql:  
    pg_hba:
      - local     all          all                            trust
      - host      all          all          0.0.0.0/0         trust
    parameters:
      max_connections: "1000"
      shared_buffers: 128MB
      effective_cache_size: 384MB
      maintenance_work_mem: 32MB
      checkpoint_completion_target: "0.9"
      wal_buffers: 3932kB
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: 3276kB
      min_wal_size: 512MB
      max_wal_size: 1GB      

