apiVersion: batch/v1
kind: Job
metadata:
  name: spark-pi-job
  namespace: default
spec:
  template:
    spec:
      serviceAccount: spark
      restartPolicy: Never
      containers:
        - name: spark-pi-job
          image: "apache/spark:3.5.0"
          imagePullPolicy: IfNotPresent
          command: ["/opt/spark/bin/spark-submit"]
          args:
            [
              "--master", "k8s://https://kubernetes.default.svc:443",
              "--deploy-mode", "cluster",
              "--name", "spark-pi-job",
              "--class", "org.apache.spark.examples.SparkPi",
              "--conf", "spark.executor.instances=2",
              "--conf", "spark.executor.memory=512m",
              "--conf", "spark.executor.cores=1",
              "--conf", "spark.driver.memory=512m",
              "--conf", "spark.kubernetes.namespace=default",
              "--conf", "spark.kubernetes.authenticate.driver.serviceAccountName=spark",
              "--conf", "spark.kubernetes.container.image=apache/spark:3.5.0",
              "local:///opt/spark/examples/jars/spark-examples_2.12-3.5.0.jar",
              "1000"
            ]